#! /bin/bash

if [ -z $1 ]; then

    echo "Sie müssen etwas eingeben, benutzung: kill [Prozessname]"

    else
    export out=$(ps -e | grep $1)

    next=$(python - <<END import os end = os.environ['out'].split(" ") if end[0]: print end[0] else: print end[1] END )

    echo "Prozess-ID " + $next

    kill -9 $next
fi
